#!/usr/bin/env python3
"""
Test Discord webhook functionality
"""

from config.config import Config
from notifiers.discord_webhook_sender import send_discord_message_webhook
import sys
import os
import logging
import asyncio

# Add the project root to the path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


def test_discord_webhook():
    """Test Discord webhook sending functionality"""

    print("[TEST] Testing Discord webhook functionality...")

    # Check if webhook URL is configured
    webhook_url = Config.DISCORD_WEBHOOK
    if not webhook_url:
        print("[ERROR] DISCORD_WEBHOOK not configured in environment variables")
        return False

    print(f"[INFO] Webhook URL configured: {webhook_url[:50]}...")

    # Test 1: Simple text message
    print("\n[TEST 1] Testing simple text message...")
    try:
        result = send_discord_message_webhook(
            "🧪 Test message from trending intelligence system!")
        if result and result.status_code == 200:
            print("[SUCCESS] Simple text message sent successfully")
        else:
            print(
                f"[FAILED] Simple text message failed: {result.status_code if result else 'No response'}")
    except Exception as e:
        print(f"[ERROR] Simple text message error: {e}")

    # Test 2: Rich embed message
    print("\n[TEST 2] Testing rich embed message...")
    try:
        embed_payload = {
            "embeds": [
                {
                    "title": "[TEST] Trending Intelligence Test Report",
                    "description": "This is a test embed from the trending intelligence system",
                    "color": 0x1e90ff,
                    "fields": [
                        {
                            "name": "[STATS] Test Stats",
                            "value": "Posts: 100 | Engagement: 85.5%",
                            "inline": True
                        },
                        {
                            "name": "[TRENDING] Test Topics",
                            "value": "#AI, #Technology, #Innovation",
                            "inline": True
                        },
                        {
                            "name": "[INSIGHT] Test Insight",
                            "value": "AI-related content is performing 35% better than average",
                            "inline": False
                        }
                    ],
                    "footer": {
                        "text": "Test • Generated by Trending Intelligence System"
                    }
                }
            ]
        }

        result = send_discord_message_webhook(embed_payload)
        if result and result.status_code == 200:
            print("[SUCCESS] Rich embed message sent successfully")
        else:
            print(
                f"[FAILED] Rich embed message failed: {result.status_code if result else 'No response'}")
    except Exception as e:
        print(f"[ERROR] Rich embed message error: {e}")

    print("\n[COMPLETE] Discord webhook test completed!")
    return True


if __name__ == "__main__":
    test_discord_webhook()
